apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

commonLabels:
  backstage.io/kubernetes-id: nodejs-dev-x03

namespace: nodejs-dev-x03

images:
- digest: sha256:1fb5c64e149eaba93a12d29e4b6f81b714c793bfeed03e5fe3362d4363798504
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay-registry-quay-quay.apps.rosa.sb1237-rosa.b20c.p3.openshiftapps.com/skitamura-quay-org/nodejs-dev-x03/nodejs-dev-x03
