apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nodejs-dev-x03-production

images:
- digest: sha256:0f420509d228099a8cd16193e8ba6a2a6582f3d5961e73e509c1e2f0c22b4919
  name: ___IMAGE_URL___@___IMAGE_DIGEST___
  newName: quay-registry-quay-quay.apps.rosa.sb1237-rosa.b20c.p3.openshiftapps.com/skitamura-quay-org/nodejs-dev-x03/nodejs-dev-x03
